site_name: Docs - UnB Avalia
repo_url: https://github.com/unb-mds/2024-1-squad04

nav:
  - Home: index.md
  - Arquitetura: arquitetura.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

  palette:
    primary: "indigo"

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
